config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :replies
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :replies
end

app/models/reply.rb
class Reply < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @reply = Reply.new
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params.merge(user_id: current_user.id))
    redirect_to posts_url
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    Reply.create(reply_params.merge(user_id: current_user.id))
  end
  def reply_params
    params.require(:reply).permit(:post_id, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/home/index.html.erb
<header>
  <nav>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Forum', :posts %> |
    <% if user_signed_in? %>
        <%= link_to('You are logged in. Logout?', destroy_user_session_path, method: :delete) %>
    <% else %>
        <%= link_to('Login', new_user_session_path)  %>
    <% end %>
  </nav>
</header>
<section>
  <article>
  <h1>Welcome <%=  %></h1>
    <% if user_signed_in? %>
        <%= link_to('You are logged in. Logout?', destroy_user_session_path, method: :delete) %>
        <br>
        <%= link_to('Edit registration', edit_user_registration_path) %>
    <% else %>
        <p>You are not logged in. You will not be able to post a thread.</p>
        <%= link_to('Login', new_user_session_path)  %> |
        <%= link_to('Sign-up', new_user_registration_path) %>
    <% end %>
  </article>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<header>
  <nav>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Forum', :posts %> |
    <% if user_signed_in? %>
        <%= link_to('You are logged in. Logout?', destroy_user_session_path, method: :delete) %>
    <% else %>
        <%= link_to('Login', new_user_session_path)  %>
    <% end %>
  </nav>
</header>
<section>
  <% if user_signed_in? %>
      <div class="new-thread">
        <p><%= link_to 'Create a new thread', new_post_path %></p>
      </div>
  <% else %>
  <% end %>
  <% @posts.each do |post|%>
    <article>
      <div class="post-demo">
        <h2>
          <%= link_to post.title, post_url(post)%>
        </h2>
        <p><%= truncate(post.content, length: 300) %></p>
        <p><%= post.created_at.strftime('%b. %e, %Y at %H:%M')%></p>
      </div>
    </article>
  <% end %>
</section>

app/views/posts/new.html.erb
<header>
  <nav>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Forum', :posts %> |
    <% if user_signed_in? %>
        <%= link_to('You are logged in. Logout?', destroy_user_session_path, method: :delete) %>
    <% else %>
        <%= link_to('Login', new_user_session_path)  %>
    <% end %>
  </nav>
</header>
<section>
  <article>
    <h1>Create a new thread</h1>
    <div class="back">
      <p><%= link_to 'Go back', :back %></p>
    </div>
    <%= form_for @post do |f| %>
      <%= f.text_field :title, placeholder: 'Title' %>
      <br>
      <%= f.text_area :content, placeholder: 'Content' %>
      <br>
      <%= f.submit %>
    <% end %>
  </article>
</section>

app/views/posts/show.html.erb
<header>
  <nav>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Forum', :posts %> |
    <% if user_signed_in? %>
        <%= link_to('You are logged in. Logout?', destroy_user_session_path, method: :delete) %>
    <% else %>
        <%= link_to('Login', new_user_session_path)  %>
    <% end %>
  </nav>
</header>
<section>
  <article>
    <div class="back">
        <p><%= link_to 'Go back', :back %></p>
    </div>
    <h2><%= @post.title %></h2>
    <p><%= @post.content %></p>
  </article>
  <div class="comments">
    <h3>Comments:</h3>
    <% @post.replies.each do |reply| %>
      <div class="comment">
        <p><%= reply.content %></p>
      </div>
    <% end %>
    <%= form_for @reply do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <% if user_signed_in? %>
          <%= f.text_area :content, placeholder: 'Write a comment...' %>
          <br>
          <%= f.submit 'Submit'%>
        <% else %>
            <p>You cannot post a comment because you are not signed in.</p>
        <% end %>
    <% end %>
  </div>
</section>